"""Accumulate PointCloud2 frames and bake them into a Gazebo heightmap.

Pipeline (real-to-sim, heightmap flavor):
  PointCloud2 (optical frame)
    -> tf2 transform into a z-up target frame (default: camera_link)
    -> range / ROI filtering (outlier rejection)
    -> rasterize: max z per grid cell (terrain top surface)
    -> fill empty cells (iterative neighbour fill)
    -> 16-bit grayscale PNG + heightmap.world (SDF)

The generated world can be loaded directly:
  ros2 launch cos_realsense view_heightmap.launch.py
"""

import os
import math

import numpy as np
from PIL import Image

import rclpy
from rclpy.node import Node
from rclpy.qos import qos_profile_sensor_data
from rclpy.duration import Duration
from sensor_msgs.msg import PointCloud2
import tf2_ros

_DATATYPES = {
    1: np.int8, 2: np.uint8, 3: np.int16, 4: np.uint16,
    5: np.int32, 6: np.uint32, 7: np.float32, 8: np.float64,
}

WORLD_TEMPLATE = """<?xml version="1.0" ?>
<!-- Auto-generated by heightmap_builder_node. -->
<sdf version="1.6">
  <world name="captured_terrain">
    <include><uri>model://sun</uri></include>
    <model name="terrain">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry>
            <heightmap>
              <uri>file://{png_path}</uri>
              <size>{size_x} {size_y} {size_z}</size>
              <pos>{pos_x} {pos_y} {pos_z}</pos>
            </heightmap>
          </geometry>
        </collision>
        <visual name="visual">
          <geometry>
            <heightmap>
              <uri>file://{png_path}</uri>
              <size>{size_x} {size_y} {size_z}</size>
              <pos>{pos_x} {pos_y} {pos_z}</pos>
            </heightmap>
          </geometry>
        </visual>
      </link>
    </model>
  </world>
</sdf>
"""


def cloud_to_xyz(msg):
    dtype = np.dtype({
        'names': [f.name for f in msg.fields],
        'formats': [_DATATYPES[f.datatype] for f in msg.fields],
        'offsets': [f.offset for f in msg.fields],
        'itemsize': msg.point_step,
    })
    data = np.frombuffer(msg.data, dtype=dtype)
    return np.column_stack([data['x'], data['y'], data['z']])


def quat_to_matrix(x, y, z, w):
    n = math.sqrt(x * x + y * y + z * z + w * w)
    x, y, z, w = x / n, y / n, z / n, w / n
    return np.array([
        [1 - 2 * (y * y + z * z), 2 * (x * y - z * w), 2 * (x * z + y * w)],
        [2 * (x * y + z * w), 1 - 2 * (x * x + z * z), 2 * (y * z - x * w)],
        [2 * (x * z - y * w), 2 * (y * z + x * w), 1 - 2 * (x * x + y * y)],
    ])


class HeightmapBuilderNode(Node):

    def __init__(self):
        super().__init__('heightmap_builder')

        self.declare_parameter('points_topic', '/camera/depth/color/points')
        self.declare_parameter('target_frame', 'camera_link')
        self.declare_parameter('num_frames', 100)
        self.declare_parameter('x_min', -0.2)
        self.declare_parameter('x_max', 3.0)
        self.declare_parameter('y_min', -1.6)
        self.declare_parameter('y_max', 1.6)
        self.declare_parameter('z_min', -0.6)
        self.declare_parameter('z_max', 0.3)
        self.declare_parameter('resolution', 0.01)
        self.declare_parameter('output_dir',
                               '/home/fit/cos_ws/app_ws/generated')

        p = lambda n: self.get_parameter(n).value
        self.target_frame = p('target_frame')
        self.num_frames = p('num_frames')
        self.x_min, self.x_max = p('x_min'), p('x_max')
        self.y_min, self.y_max = p('y_min'), p('y_max')
        self.z_min, self.z_max = p('z_min'), p('z_max')
        self.res = p('resolution')
        self.output_dir = p('output_dir')

        self.nx = int(round((self.x_max - self.x_min) / self.res))
        self.ny = int(round((self.y_max - self.y_min) / self.res))
        self.grid = np.full((self.ny, self.nx), -np.inf, dtype=np.float64)
        self.frames_used = 0
        self.done = False

        self.tf_buffer = tf2_ros.Buffer()
        self.tf_listener = tf2_ros.TransformListener(self.tf_buffer, self)

        self.sub = self.create_subscription(
            PointCloud2, p('points_topic'), self.cloud_callback,
            qos_profile_sensor_data)
        self.get_logger().info(
            'Collecting %d frames of %s into a %dx%d grid (%.0f mm/cell)'
            % (self.num_frames, p('points_topic'), self.nx, self.ny,
               self.res * 1000))

    def cloud_callback(self, msg):
        if self.done:
            return

        try:
            tf = self.tf_buffer.lookup_transform(
                self.target_frame, msg.header.frame_id,
                rclpy.time.Time.from_msg(msg.header.stamp),
                timeout=Duration(seconds=1.0))
        except (tf2_ros.LookupException, tf2_ros.ConnectivityException,
                tf2_ros.ExtrapolationException) as e:
            self.get_logger().warn('TF lookup failed: %s' % e,
                                   throttle_duration_sec=5.0)
            return

        t = tf.transform.translation
        q = tf.transform.rotation
        R = quat_to_matrix(q.x, q.y, q.z, q.w)

        xyz = cloud_to_xyz(msg)
        xyz = xyz[np.isfinite(xyz).all(axis=1)]
        if xyz.size == 0:
            return
        pts = xyz @ R.T + np.array([t.x, t.y, t.z])

        # ROI filter: keep only points inside the mapped region
        mask = ((pts[:, 0] >= self.x_min) & (pts[:, 0] < self.x_max)
                & (pts[:, 1] >= self.y_min) & (pts[:, 1] < self.y_max)
                & (pts[:, 2] >= self.z_min) & (pts[:, 2] <= self.z_max))
        pts = pts[mask]
        if pts.size == 0:
            return

        ix = ((pts[:, 0] - self.x_min) / self.res).astype(np.int32)
        iy = ((pts[:, 1] - self.y_min) / self.res).astype(np.int32)
        # max z per cell = top surface of the terrain
        np.maximum.at(self.grid, (iy, ix), pts[:, 2])

        self.frames_used += 1
        if self.frames_used % 25 == 0:
            filled = np.isfinite(self.grid).mean() * 100.0
            self.get_logger().info(
                'frames %d/%d, grid coverage %.1f%%'
                % (self.frames_used, self.num_frames, filled))
        if self.frames_used >= self.num_frames:
            self.bake()

    def bake(self):
        grid = self.grid.copy()
        filled = np.isfinite(grid)

        # Iteratively fill empty cells with the mean of filled neighbours.
        for _ in range(50):
            if filled.all():
                break
            acc = np.zeros_like(grid)
            cnt = np.zeros_like(grid)
            for dy, dx in ((0, 1), (0, -1), (1, 0), (-1, 0)):
                shifted = np.roll(grid, (dy, dx), axis=(0, 1))
                valid = np.roll(filled, (dy, dx), axis=(0, 1)) & ~filled
                acc[valid] += shifted[valid]
                cnt[valid] += 1
            newfill = (~filled) & (cnt > 0)
            grid[newfill] = acc[newfill] / cnt[newfill]
            filled |= newfill
        grid[~filled] = self.z_min

        # Gazebo requires heightmap images to be square with side 2^n + 1,
        # otherwise gzclient segfaults. Resample (bilinear) to the nearest
        # such size; physical extents are kept by the world <size> tag.
        n = max(1, int(np.ceil(np.log2(max(self.nx, self.ny) - 1))))
        side = 2 ** n + 1
        if grid.shape != (side, side):
            grid = np.array(Image.fromarray(
                grid.astype(np.float32), mode='F').resize(
                    (side, side), Image.BILINEAR))

        # Normalize z range -> 16-bit grayscale
        size_z = self.z_max - self.z_min
        img = ((grid - self.z_min) / size_z * 65535.0).clip(0, 65535)
        png = Image.fromarray(img.astype(np.uint16), mode='I;16')

        os.makedirs(self.output_dir, exist_ok=True)
        png_path = os.path.join(self.output_dir, 'heightmap.png')
        png.save(png_path)

        world_path = os.path.join(self.output_dir, 'heightmap.world')
        with open(world_path, 'w') as f:
            f.write(WORLD_TEMPLATE.format(
                png_path=png_path,
                size_x=self.x_max - self.x_min,
                size_y=self.y_max - self.y_min,
                size_z=size_z,
                pos_x=(self.x_min + self.x_max) / 2.0,
                pos_y=(self.y_min + self.y_max) / 2.0,
                pos_z=self.z_min))

        self.get_logger().info('Heightmap written:')
        self.get_logger().info('  PNG:   %s (%dx%d)' % (png_path, side, side))
        self.get_logger().info('  World: %s' % world_path)
        self.get_logger().info('View it with: ros2 launch cos_realsense view_heightmap.launch.py')
        self.done = True


def main(args=None):
    rclpy.init(args=args)
    node = HeightmapBuilderNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
